version: "3.1"
services:
  web:
    build: .
    ports:
      - "1405:1405"
      - "5432:5432"  # Uncomment to expose db's port
    volumes:
      - ./:/code
    entrypoint: ./init.sh
    restart: unless-stopped

  db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=url_customizer
    volumes:
      - .data/db/:/var/lib/postgresql/data
    restart: always
    network_mode: service:web
