version: "3"
services:
  web:
    build: .
    ports:
      - "1405:1405"
    volumes:
      - ./:/code
    entrypoint: ./init.sh
    network_mode: host
    restart: unless-stopped

  db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=url_shortener
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data
    restart: always

volumes:
  db:
    driver: local
