"""Initial migration

Revision ID: a16ab12bc1e8
Revises: 
Create Date: 2022-11-14 14:20:44.928717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a16ab12bc1e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortened_url',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('custom_url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('custom_url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shortened_url')
    # ### end Alembic commands ###
