"""empty message

Revision ID: ee102b63890d
Revises: 
Create Date: 2022-12-06 20:35:37.655205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee102b63890d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customized_url',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('custom_url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('custom_url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customized_url')
    # ### end Alembic commands ###
